# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxcomputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('uno',),
                'verbose_name': 'boxcomputer',
                'verbose_name_plural': 'boxcomputers',
            },
        ),
        migrations.CreateModel(
            name='Boxconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pc', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('customer', 'uno', 'ram', 'storage', 'Osys', 'slug'),
                'verbose_name': 'boxconfig',
                'verbose_name_plural': 'boxconfigs',
            },
        ),
        migrations.CreateModel(
            name='BoxPCDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno_serial', models.CharField(max_length=20, unique=True)),
                ('ram_serial', models.CharField(max_length=200, unique=True)),
                ('hd_serial', models.CharField(max_length=200, unique=True)),
                ('product_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('extra', models.CharField(blank=True, max_length=200)),
                ('total_pc', models.IntegerField()),
                ('assembled_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('customer', 'configuration_no', 'uno_serial', 'product_key', 'total_pc', 'slug'),
                'verbose_name': 'boxpcdetail',
                'verbose_name_plural': 'boxpcdetails',
            },
        ),
        migrations.CreateModel(
            name='Chasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipc', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('ipc',),
                'verbose_name': 'chasis',
                'verbose_name_plural': 'chasiss',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pc', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('customer', 'ipc', 'mboard', 'cpu', 'ram', 'storage', 'Osys', 'slug'),
                'verbose_name': 'configuration',
                'verbose_name_plural': 'configurations',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('customer',),
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('engineer',),
                'verbose_name': 'engineer',
                'verbose_name_plural': 'engineers',
            },
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Humachininterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmi', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('hmi',),
                'verbose_name': 'humamachineinterface',
                'verbose_name_plural': 'humachininterfaces',
            },
        ),
        migrations.CreateModel(
            name='IndustrialPCDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipc_serial', models.CharField(max_length=20, unique=True)),
                ('am_serial', models.CharField(max_length=20, unique=True)),
                ('smps_serial', models.CharField(max_length=200, unique=True)),
                ('ram_serial', models.CharField(max_length=200, unique=True)),
                ('hd_serial', models.CharField(max_length=200, unique=True)),
                ('product_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('extra', models.CharField(blank=True, max_length=200)),
                ('total_pc', models.IntegerField()),
                ('assembled_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('assembled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrialpcdetails', to='mainapp.Engineer')),
                ('configuration_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrialpcdetails', to='mainapp.Configuration')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrialpcdetails', to='mainapp.Customer')),
            ],
            options={
                'ordering': ('customer', 'configuration_no', 'ipc_serial', 'product_key', 'total_pc', 'slug'),
                'verbose_name': 'industrialpcdetail',
                'verbose_name_plural': 'industrialpcdetails',
            },
        ),
        migrations.CreateModel(
            name='IPPCDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ippc_serial', models.CharField(max_length=20, unique=True)),
                ('ram_serial', models.CharField(max_length=200, unique=True)),
                ('hd_serial', models.CharField(max_length=200, unique=True)),
                ('product_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('extra', models.CharField(blank=True, max_length=200)),
                ('total_pc', models.IntegerField()),
                ('assembled_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('assembled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ippcdetails', to='mainapp.Engineer')),
                ('configuration_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ippcdetails', to='mainapp.Configuration')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ippcdetails', to='mainapp.Customer')),
            ],
            options={
                'ordering': ('customer', 'configuration_no', 'ippc_serial', 'product_key', 'total_pc', 'slug'),
                'verbose_name': 'ippcdetail',
                'verbose_name_plural': 'ippcdetails',
            },
        ),
        migrations.CreateModel(
            name='Ippconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pc', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('customer', 'ippc', 'ram', 'storage', 'Osys', 'slug'),
                'verbose_name': 'boxconfig',
                'verbose_name_plural': 'boxconfigs',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('ram',),
                'verbose_name': 'memorie',
                'verbose_name_plural': 'memories',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('part_no',),
                'verbose_name': 'motherboard',
                'verbose_name_plural': 'motherboards',
            },
        ),
        migrations.CreateModel(
            name='Operatingsys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('O_sys', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('O_sys',),
                'verbose_name': 'operatingsys',
                'verbose_name_plural': 'operatingsyss',
            },
        ),
        migrations.CreateModel(
            name='Powersupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smps', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('smps',),
                'verbose_name': 'powersupply',
                'verbose_name_plural': 'powersupplys',
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('cpu',),
                'verbose_name': 'processor',
                'verbose_name_plural': 'processors',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_type', models.CharField(max_length=20)),
                ('s_size', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('s_type', 's_size'),
                'verbose_name': 'storage',
                'verbose_name_plural': 'storages',
            },
        ),
        migrations.AddField(
            model_name='ippconfig',
            name='Osys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ippconfigs', to='mainapp.Operatingsys'),
        ),
        migrations.AddField(
            model_name='ippconfig',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ippconfigs', to='mainapp.Customer'),
        ),
        migrations.AddField(
            model_name='ippconfig',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ippconfigs', to='mainapp.Extras'),
        ),
        migrations.AddField(
            model_name='ippconfig',
            name='ippc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ippconfigs', to='mainapp.Humachininterface'),
        ),
        migrations.AddField(
            model_name='ippconfig',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ippconfigs', to='mainapp.Memory'),
        ),
        migrations.AddField(
            model_name='ippconfig',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ippconfigs', to='mainapp.Storage'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Osys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='mainapp.Operatingsys'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='mainapp.Processor'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='mainapp.Customer'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='mainapp.Extras'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ipc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='mainapp.Chasis'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='mboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='mainapp.Motherboard'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='mainapp.Memory'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='smps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='mainapp.Powersupply'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='mainapp.Storage'),
        ),
        migrations.AddField(
            model_name='boxpcdetail',
            name='assembled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxpcdetails', to='mainapp.Engineer'),
        ),
        migrations.AddField(
            model_name='boxpcdetail',
            name='configuration_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxpcdetails', to='mainapp.Configuration'),
        ),
        migrations.AddField(
            model_name='boxpcdetail',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxpcdetails', to='mainapp.Customer'),
        ),
        migrations.AddField(
            model_name='boxconfig',
            name='Osys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxconfigs', to='mainapp.Operatingsys'),
        ),
        migrations.AddField(
            model_name='boxconfig',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxconfigs', to='mainapp.Customer'),
        ),
        migrations.AddField(
            model_name='boxconfig',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxconfigs', to='mainapp.Extras'),
        ),
        migrations.AddField(
            model_name='boxconfig',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxconfigs', to='mainapp.Memory'),
        ),
        migrations.AddField(
            model_name='boxconfig',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxconfigs', to='mainapp.Storage'),
        ),
        migrations.AddField(
            model_name='boxconfig',
            name='uno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxconfigs', to='mainapp.Boxcomputer'),
        ),
    ]
